### ISSUE TITLE
Size of zoom image

### ISSUE THREAD

**Issue by msollmann** [fnagel/generic-gallery#53]
I haven't found a possibility to configure the max size of the zoom image. Is there any?

**Comment by fnagel** [comment]
Can you point out where exactly you need this? 

In general, this should be easily possible using Fluid core view helpers, like described here: https://docs.typo3.org/other/typo3/view-helper-reference/11.5/en-us/typo3/fluid/latest/Uri/Image.html
Just use it as replacement for the `publicUrl` property here: https://github.com/fnagel/generic-gallery/blob/master/Resources/Private/Templates/GalleryItem/Show.html#L20-L23

Does this help?

**Comment by msollmann** [comment]
I meant the size of the zoom image which is given as {item.link} in https://github.com/fnagel/generic-gallery/blob/master/Resources/Private/Partials/GalleryItem/Image.html. Is there a possibility to configure this by TS oder template?

**Comment by fnagel** [comment]
Ahh ok, no, there is no option by default, as the link getter just falls back to the public URL if no link is set, see: https://github.com/fnagel/generic-gallery/blob/master/Classes/Domain/Model/GalleryItem.php#L161

Anyway, it's possible to use the image uri VH (instead of the getter) and add own TS settings!

Something like:
```
<f:link.typolink parameter="{f:uri.image(image: item.image, width: 1200, height: 800)}">
	...
</f:link.typolink>
```

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by msollmann** [comment]
Thank you for your description of defining an image size for the zoom image.
